apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::903438821308:role/lighthouse-prod20211030094654635700000009
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
    - rolearn: arn:aws:iam::903438821308:role/AWSReservedSSO_AWSAdministratorAccess_5461ea9b3409d81a
      username: adminuser:{{SessionName}}
      groups:
        - system:masters
        - default:eks-admins
    - rolearn: arn:aws:iam::903438821308:role/AWSReservedSSO_EKSAdmins_6bd4134ffdb22377
      username: adminuser:{{SessionName}}
      groups:
        - system:masters
        - default:eks-admins
     - rolearn: arn:aws:iam::903438821308:role/AWSReservedSSO_OperationsElevatedAccess_f7363c4f50e07eb1
      username: adminuser:{{SessionName}}
      groups:
        - system:masters
        - default:eks-admins
        
        
        
        
